CREATE TABLE T_PANEL_PNL
(PNL_NOM VARCHAR(16),
 PNL_REPONSE1 INTEGER,
 PNL_REPONSE2 INTEGER,
 PNL_REPONSE3 INTEGER,
 PNL_REPONSE4 INTEGER,
 PNL_REPONSE5 INTEGER); 

CREATE TABLE T_REPONSES_RPS
(RPS_REPONSE1 INTEGER, 
 RPS_REPONSE2 INTEGER, 
 RPS_REPONSE3 INTEGER,
 RPS_REPONSE4 INTEGER, 
 RPS_REPONSE5 INTEGER); 


INSERT INTO T_PANEL_PNL VALUES ('Pierre',  1, 2, 3, 0, 0); 
INSERT INTO T_PANEL_PNL VALUES ('Paul',    1, 5, 3, 2, 1);
INSERT INTO T_PANEL_PNL VALUES ('Jacques', 0, 3, 3, 2, 2); 

INSERT INTO T_REPONSES_RPS VALUES (1, 4, 3, 2, 1); 


SELECT * from T_PANEL_PNL ;
SELECT * FROM T_REPONSES_RPS ;

