
WITH
    TBL1 AS (
        SELECT (COUNT(DISTINCT TBL1.TBL_ID)) as tbl1 from TBL1 CROSS JOIN TBL2 CROSS JOIN TBL3
    ),
    TBL2 AS (
        SELECT (COUNT(DISTINCT TBL2.TBL_ID)) as tbl2 from TBL1 CROSS JOIN TBL2 CROSS JOIN TBL3
    ),
    TBL3 AS (
        SELECT (COUNT(DISTINCT TBL3.TBL_ID)) as tbl3 from TBL1 CROSS JOIN TBL2 CROSS JOIN TBL3
    )
SELECT * FROM tbl1, tbl2, tbl3;

